services:
  django-app:
    image: ghcr.io/jorgelg3/thejorgelab-blog:latest
    restart: unless-stopped
    ports:
      - 8000:8000
    volumes:
      - data/db:/app/db
      - data/media:/app/media
    environment:
      DEBUG: false
      SECRET_KEY: ${SECRET_KEY}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}