# Generated by Django 6.0.5 on 2026-05-27 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='about/'),
        ),
    ]
